# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=30)),
                ('type', models.CharField(default='Dublado, 2D', max_length=30)),
                ('faixa', models.CharField(default='0', max_length=20)),
                ('time', models.DurationField()),
                ('date', models.DateTimeField()),
                ('cinema', models.CharField(max_length=30)),
                ('shopping', models.CharField(max_length=30)),
                ('cidade_uf', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('elenco', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
