# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='cidade_uf',
            field=models.CharField(default='Cidade-UF', max_length=30),
        ),
    ]
