# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msi', '0002_auto_20171022_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='faixa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
