# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msi', '0003_auto_20171022_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='url_img',
            field=models.CharField(default='.png', max_length=100),
        ),
    ]
