# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msi', '0005_auto_20171024_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='cinema',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='faixa',
            field=models.CharField(default='.png', max_length=300),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='shopping',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='type',
            field=models.CharField(default='Dublado, 2D', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='url_img',
            field=models.CharField(default='.png', max_length=300),
        ),
    ]
