# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msi', '0007_auto_20171024_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('type', models.CharField(default='Dublado, 2D', max_length=20)),
                ('faixa', models.CharField(default='.png', max_length=300)),
                ('time', models.DurationField()),
                ('director', models.CharField(max_length=30)),
                ('elenco', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msi.Categ')),
            ],
        ),
        migrations.RemoveField(
            model_name='sessao',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sessao',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sessao',
            name='director',
        ),
        migrations.RemoveField(
            model_name='sessao',
            name='elenco',
        ),
        migrations.RemoveField(
            model_name='sessao',
            name='faixa',
        ),
        migrations.RemoveField(
            model_name='sessao',
            name='time',
        ),
        migrations.RemoveField(
            model_name='sessao',
            name='type',
        ),
        migrations.AddField(
            model_name='film',
            name='sessions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msi.Sessao'),
        ),
    ]
