# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msi', '0008_auto_20171024_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessao',
            name='url_img',
        ),
        migrations.AddField(
            model_name='film',
            name='url_img',
            field=models.CharField(default='.png', max_length=300),
        ),
    ]
