# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msi', '0009_auto_20171024_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='category',
        ),
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(to='msi.Categ'),
        ),
        migrations.RemoveField(
            model_name='film',
            name='sessions',
        ),
        migrations.AddField(
            model_name='film',
            name='sessions',
            field=models.ManyToManyField(to='msi.Sessao'),
        ),
    ]
