# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('msi', '0010_auto_20171024_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
