# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msi', '0011_film_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='link',
            field=models.CharField(default='link', max_length=50),
        ),
    ]
