# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msi', '0012_film_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='category',
        ),
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='msi.Categ'),
        ),
        migrations.RemoveField(
            model_name='film',
            name='sessions',
        ),
        migrations.AddField(
            model_name='film',
            name='sessions',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='msi.Sessao'),
        ),
    ]
